
MACRO(CONFIGURE_V3D_PLUGIN PLUGIN_GROUP_NAME PLUGIN_NAME)

INCLUDE_DIRECTORIES( ${CMAKE_SOURCE_DIR} )

SET(QtITK_SRCS ${PLUGIN_NAME}.cxx )

QT4_WRAP_CPP(QT_MOC_SRCS ${PLUGIN_NAME}.h)

ADD_LIBRARY(${PLUGIN_NAME} SHARED ${QtITK_SRCS} ${QT_MOC_SRCS})
TARGET_LINK_LIBRARIES(${PLUGIN_NAME} ITKIO ${QT_LIBRARIES})

INSTALL(TARGETS ${PLUGIN_NAME}
  LIBRARY DESTINATION ${INSTALLATION_DIRECTORY}/${PLUGIN_GROUP_NAME} COMPONENT RuntimeLibraries
  PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
  )

ENDMACRO(CONFIGURE_V3D_PLUGIN)
